name: AI Agents Ticketing System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.3'

      - name: Install dependencies
        run: |
          python -m venv venv_lib
          source venv_lib/bin/activate
          pip install --upgrade pip
          pip install -r Ideas/ai_agents_ticketing_system/requirements.txt

      - name: Run Application and Health Check
        run: |
          source venv_lib/bin/activate
          cd Ideas/ai_agents_ticketing_system
          nohup uvicorn main:app --host=127.0.0.1 --port=8000 --reload > uvicorn.log 2>&1 &
          sleep 15
          echo "=== Uvicorn Logs ==="
          cat uvicorn.log
          echo "===================="
          curl --fail http://127.0.0.1:8000 || (echo "App did not respond" && exit 1)
